### ISSUE TITLE
elogind support

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#146]
I noticed cloudef/wlc#279 and we could easily do that as well.
I don't want to blindly add code I can't test, so if someone on a non-systemd system could try this and see if it doesn't break anything, that would be great.

**Comment by Dudemanguy911** [comment]
Oh unfortunately it's not quite as easy here otherwise I would have done it already. On wlroots, logind.c depends on a lot of systemd-specific functions (ex. sd_bus_get_fd) that wouldn't be available on elogind setups. Either logind.c would have to be rewritten to use non-sd-bus functions or a separate logind implementation would need be to written (perhaps named elogind.c)

**Comment by ascent12** [comment]
Doesn't elogind also provide sd-bus?

**Comment by Dudemanguy911** [comment]
Yes, but not every function. I haven't taken the time to thoroughly explore which ones are missing or why some headers are included in path and why others aren't.

**Comment by ascent12** [comment]
`sd_bus_get_fd` seems like an extremely odd choice for them to leave out, especially since they still have `sd_bus_set_fd`. I seems like they're removing everything that they're not using internally, and don't actually care about the sd-bus API.
Quickly glancing over https://github.com/elogind/elogind/blob/master/src/systemd/sd-bus.h, that seems to be the only missing function we're using.

We could try asking them to uncomment that one function.

**Comment by Dudemanguy911** [comment]
That's likely the best course of action. I've just asked them at elogind/elogind#30, so hopefully resolving that can also take care of this issue.
